server:
  port: 40002
  servlet:
    session:
      cookie:
        same-site: strict
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: houber-city;
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(cR1lVrscKe+ScuVh1R5uOFgIpbKdunx9L29qp9s+CHpjRJLiKEApu3sTU6HLDzXWHWYa8+pKB5mDXWXayo9B3zbak43OzpkD+fNNNXMkrRnob2ECm4Yg7HbUpGYnGQRDzBD83T62XkQ=)
    username: ENC(bLOV1rhg9qGgt4R9n83J4fEcY6zmIMZe)
    password: ENC(QqOaryyb5bffJFi2dMss5OdV+bY50SFY)
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 100
          max-idle: 30
          min-idle: 5
          max-wait: 5000
      password: ENC(c1UTTrEa7dcw6s2hMFu5tTsKqzzmMjZXR85zgR89CwM=)

aws:
  anthropic:

  s3:
    region: ENC(GevVIOftUrRRRDmncI/QSGI8RoUasFBi)
    accessKey: ENC(ePjaFE8nbgVjLaq49B4deEQxS8dGjmxWaZ/3mjTlQhU=)
    secretKey: ENC(zFq4ytl1Q0b0rMTl8sgzgv4OOLfHKt4a7JA4FttvyZkKbpkdeP3tnwvFsb5cm3Xm+OV07x81Ba4=)
    bucket-name: ENC(KRnbh8euVkW/ol0eoHd3SiKEwWwTXCKW)

google:
  console:
    key: ENC(L2qsqAGG9N3+QjIdRlMw587smurMAxkLYVQLgpicr2gt1p1+PT3AhQngmYAZ7miF)
naver:
  client:
    X-Naver-Client-Id: ENC(t0Hzsyqe5wjzw56/oWmCjsqEKFbNxEnksZ917Tydmkg=)
    X-Naver-Client-Secret: ENC(OEdF/bm1fM2/3vscbzEZ+Uu3iGHb75jT)
realnetpro:
  id: ENC(cvQaNwIRc0qjlF+wpatPEzGw5mDZTh6j)
  pw: ENC(bsGZyCCDMXd1MCpRQHaDMhO6BzT6oBDi)

ai:
  key: ENC(bcQdPpw+SKU1lj9xlU78g5wyhMxAualZTpVks1H3ZQZ37dacwlgF+LOI0yjUHU5kLvLFlT4Abf3cWSi18u9docAcWwWo7HSaTdZ6c7VhKec5c69SB5ed1NYNG6IZpmEHHlM4Y9qx+4QzB6Hxg4hoqxG4ZBzqbenyUB6BRpHsPav1G8s6MAqPKPDK3xoERhzqqtJ28/B1RUJwoK0pMPxL8JRuHHu+Wy7rLNCHN26pUmw=)
